# Generated by Django 2.2.7 on 2019-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hdurl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
