# Generated by Django 2.2.7 on 2019-11-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0004_comment_like_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments_photo', to='stars_app.Photo'),
            preserve_default=False,
        ),
    ]
