# Generated by Django 2.2.7 on 2019-11-11 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0009_auto_20191108_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlikes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
